  runtime: python37
  entrypoint: gunicorn -b :$PORT wishlist.wsgi

  handlers:
  - url: /static
    static_dir: www/static/

  - url: /.*
    script: auto

  env_variables:
    TRAVELER_PW: Strangerdanger

  beta_settings:
    cloud_sql_instances: braided-analyst-295416:us-central1:wishlist-db